apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicgames-freegames
  labels:
    app.kubernetes.io/name: epicgames-freegames
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: epicgames-freegames
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epicgames-freegames
    spec:
      volumes:
        - name: epicgames-config
          persistentVolumeClaim:
            claimName: epicgames-freegames-pvc
      containers:
        - name: epicgames-freegames
          image: ghcr.io/claabs/epicgames-freegames-node:latest
          envFrom:
            - configMapRef:
                name: epicgames-freegames-configmap
            - secretRef:
                name: epicgames-freegames-secrets
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: epicgames-config
              mountPath: "/usr/app/config"
          resources:
            limits:
              memory: 2G
