---
- name: Clone from template VM-{{ vm.key }}
  ansible.builtin.import_tasks: create_vm_clone.yaml
  when: vm.value.template is defined

- name: Create standalone VM-{{ vm.key }}
  ansible.builtin.import_tasks: create_vm_scratch.yaml
  when: vm.value.template is not defined
