---
- name: Remove pve-enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve trixie pve-enterprise
    state: absent
    update_cache: true
    filename: pve-enterprise

- name: Add pve-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve trixie pve-no-subscription
    state: present
    update_cache: true
    filename: pve-no-subscription
