---
- name: Remove subscription prompt
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: "data\\.status\\.toLowerCase\\(\\) !== 'active'"
    replace: "false"
    backup: true
