---
arch: amd64

templates:
  debian-trixie:
    id: 105
    url: https://cdimage.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
    storage: local-lvm

vms:
  lix-test:
    id: 104
    template: 105
    cores: 2
    ram: 2048
    autoboot: true
    cloudinit:
      user: prettysunflower
      ssh_keys: "{{ ssh_keys }}"
    ipconfig:
      0:
        dhcp: true
    network:
      0:
    cd:
      ide0:
        iso: debian-13.2.0-amd64-netinst.iso
        storage: local
    disks:
      scsi0:
        storage: local-lvm
        size: 32
  media:
    id: 107
    template: 105
    cores: 2
    ram: 4096
    autoboot: true
    cloudinit:
      user: prettysunflower
      ssh_keys: "{{ ssh_keys }}"
    ipconfig:
      0:
        dhcp: true
    network:
      0:
    disks:
      scsi0:
        storage: local-lvm
        size: 32
