cloudinit_passwords:
  lix-test: ENC[AES256_GCM,data:LiClkcHY,iv:PGVySS9UiH18KB58pDkS7OUzczZkrizArH6kx1JmbqQ=,tag:SRmHh2jPRa5fdugBe+ROZw==,type:str]
  yul-okina: ENC[AES256_GCM,data:AwxvWW6nj6kxTVqfs36AUHYkroU=,iv:fXWSj/LARlNuJSPf+yn0NDUCH+sXZhaNmsEIepszTBI=,tag:qIlc9w+EmUS673IwtVGjNA==,type:str]
sops:
  age:
    - recipient: age1pq15jdu8xuhs350gqry8d0qc3q48y26jmdye55utf4dwrz0usxd7cje7v4sjm92k0spkw3kg2zxezvjr4vyk8dtsqn5trzmr5xzm02f20urxta9kgsa4zh7c7ttzrpssg86naua3dw8j9e479mspcugt89rq047hd4zks9m4kr86xqpttfvzmx3gmphsa3fg962ecm472w8kna2e2hcqf0267regfr9z55p932gnqshms732gj3mxec3399fuhzxkdtrwqf4dra8ngy9z79hh67rjguqfzkh63x2dszfsrrszr4cxm6w0qftequn5ts3nfryx3lyshr02rp8z9yms5qqurpvg8w003zj97aaxejde5ne795pmgy03sm57dgelqp9kd9svguvd7r2thmcpaqxk2x8mjmety4e85lpnt3fph0d8z0evzj49fg2mg4d2qmkam3e5y9jfzhnwt5z5t4g80dgqg2ua32rp63nfmpql58z03cykc6jnpcdt9mqr4n387ss0p9996m0efwxzv2hhvpdsehp90vl28s4udqkmxy0dy49tglyzntx4d9nwg3pkvyeh99zvha024pnqrcey7qt7x22l2nv04ynpnwx3jhnguu06jm60ffvackp0a5ashp4wtfkq949dlnga8vq2s5a2pcfqycrk3uz8n6r7gz283rv5xeacf4l03sepjhrg0wrgmf5m8r0cjzettmekuh820dj5un5x30q36hr35h6gy9y2g8sum36yflaj3g5jmqtah8y94427k2xkt204fd4ev2zqrv898rnrvquu5u0qgwfp6kl82yypt5pq5qey3ffq25sfyk4q0h2yluv3d0h9s0yxa74fp3gtcxc0yyqejtyz3vjz52hv6qmxw8sg6049s576wfqps6sueq90zngafk2tc7xwq8fffzcdw2yzsswg3w90zg5tyy37xt056xxmmzdcvqefqyxgzn05mdgnt3yhz6yqslq9q8lp3tuv29hjazvz0edudfvaccygx5xwejq84c8a39frd6r2th4wf05srxg9kgj3x5jjdgtrwsz0y5t653tmufnny5c4ghgdaq6s4qvuungax9z2m63h40srvv0qw6cq3vgkgruf0mrcaljk6gqaalvq2zn3fhy9gm404qsqy0w9vyaky9ggukvpjfscmujqatguhta5c80ye5634h2sukq7wwdv2kykpwc5je4lpvp6z7ss64xuhsl7vzz2d2z7aftd550j4p2k27pxepf8fj6xu4t0jgrqvluqd9ffkpttjgtr0mwynppwj757l4heyjr9exl35gj2x5y6pfk42qywpeuuvvsa93wad3j7rvej7qk9glqjt830r55l6cydc34pk9xpn9fk32kq5hzukrqz2zy9nfecf3swcqkuqf2lty5l2tpgxk45zudww9uht8numeeplde360mxv2qe35vkf6p86fw9wfkp7pw2gpeys3wmjzjw2vty8xjdjqpaaxmzm8zz42rvw2xkqyq4xvjyp3tpv5auq6hgltfp4alzexxtzdcdgsauk89dd0qypdk9jynfaeqcvxzukmz3rtxcm8652z2aaer6crzuh54e6mrx5632xl9vxtrhy6qz4ftqehx375gp4eh7s6gp6qm36kjef02alpzqgrn3mlxc2cj3r8hrga5r8uhsp8vzg3nkf5r8rm2dyk9vhdq3d889z4z9d4gj4myqmte0sp6k0e33ff9xq4y7g48p090ym9fjuralz09gru0lck2xe5x3avq2lt58pjadghjar3nt34klh0ds7lfuacqt44lrgpy2fcv9twslydqvvghycra0usmg9emytdhr5x2f86jqz0lrz38l4k9srfq385z7ewugskeffgkv5ysdzpz86yme6t4jk3fuarhqg6sarf7srp26wqzcwdmrtv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE1nZzhHaWgz
        TnEyTkhrd3dTYzlUY0R5NnRueUM2VzRaZUw0azZBMmw5QkN4NmJTYkpnell4QUlu
        OWhGWUpBblNUYWFkQ0QvNDdZWEI5cTNuZnNCUlJVMFVCNFJjaFRZRHRxOVBLYUpJ
        Qkl6M0Q5Vys2aUszTkt0OUgvMnBlRlRNSVNjRi9IT0kzOVJBM3lEWllYNHhPcENO
        UzVsVU10TGVRNmhOZVhKcGtIbDFhV0RvVkltL3gvUVdua1lTbUVkSEx6cUVvcitM
        Mkx0SDNsN1E2eVV3clRzZkdVNjBoYTZiV1NvSzFNc25mRmxCRHBLRTF3cHhMdHow
        WDl0NXFnK3RoeHBlODdDd0ZyM0h1eEdJcjBKcmpXVVIwZzFaUGkyZFVqZytkQTF5
        VE84aTdGUitoYnNPK1NoK3dLcXByeWx3d05BSGZEYTJ0ZWR3cVlKYVlTVUF4aUMx
        eFRPRmhaR1BCRFN3RmhHbmRtY1V3NkFSZFM2czREVDNneWR4NmJqV0hwVTZZNzRs
        d1lqZHhmZWtYeXZRaHFDbVJYQXNLSVU3OUY0cThzc0NQWW02dU9oNXN2aHllM0Rs
        ekoyU0NtaWV4MUhtSWhiZkVFZktzYktlNGJEVFI5QWo1NUJYRHBhekZkS0RPQkFS
        bWhPenZSQlNIZEdYdEtHUnhhb0x3NkxmN2xuWkR1a3RYaDh5UEg2L2d2TDdLaUp3
        bnM1cC92UkFTTmxCVWJUc2taWFhYOUNoNGIwNWY4WXJWbFlSNDAxNU1iUlR3QUp0
        ZzBGMzgvbk9BYVkzWURnM3RCMU52RmowLzRYYmptMUFwdHVwZjZlZHhlMFRzaFRW
        cGVXWUlSbHRpLzR1eXE2UmQ0S3NiR3VvSTBFNlNsMWtzS0VubmJiR1RnMUZHYndP
        S2tUenJpR2xlelNUaVlLM3lvZDhKY2hGM0MxcE5TdEQ1MFRCWkluQmRic3pMOEpE
        QjFFalZ5U0pERVExZFpiRWZWSnpuNkk2akxDbzcrY1Jnc2dRR1JScHc3a21kZDNw
        WmNvSEJRbmNOWVUrVDV2SEp3V1FKYXlGOTZaU0VsMWE5M1YrMUMvR0daVkRhMjhO
        MmNXd2tPTFhIT2xNZFIzSTQ1bDI5ZERnT3hDRjZJc3ZWaytGMDR3UlIvRUl5VkYv
        QmJCSWZBcFJhcThmbHl4NGNnbCs4NmtLT2J1aUJOUWMvRVNWK2QzU0NXdjVWUlFx
        MytGcndYa0sxVXZub1oxTlkyRFdnZU9Odjl3dElFZ3hrQWsxT2VTZlR4OEttRXQy
        Mkw1bmY4TE1hbjNuOG8zTXplUGMvdGQ4Tm5ZZzRWUHRMelVSekx5S3JJNE5URlRt
        YnFDd3JKWWVvL0Y0R2o5ZEJja0JvcWlsMUxPZ3pLOVg5TUs2VHlTZS9LbHNCZ2Mw
        SWREZ2RJYUE0OXBlWEppVS9GQ1c0KzE5WWpBQ1BsbjJPSDR4M1BVZkZTYTI4TnRm
        QStaRms3Uk50WXNUYmRlN2xlWkhSVjU0QkYwaE1zQ1c0TEdDZHkrSjhaRVRvVWFD
        OUc5WGlUdTVYaDZSUTB1T2VNcXNGQTVIT3ZmWXZRSXRka0FUSU1hcSt5QXV2V3hk
        V0Z6d2pMclJEOHVGcGpmSHBmVWhRU2UvaE5zS0tCNXdEaDlyblNjak9BdEhIN3VK
        d1Fab0M3WkNRWW45RXdJZXAxN0MvMUdKRHY5SGY2UnZQdkZCS3R2cjl2dVN1REl0
        c3FaTmdJbHVnM1ZNMkZucWNmZTlNQnBjdGk4WjlrZzVVQlBTQ2QzU3NXNi94U0J3
        SVpENWVaNzlKbTc1T2h1eUkzaUpxbzlScStBTjNHa294T2owSGZxNjVuS3BjZ2N6
        b1ErVWk1QjdyZW16c3JOSEFiYVVMR3RYdGRNaXdqdlo4SW9XdWRidlp4N0k5SHk0
        V3kxeU0ya1duOXg3THdScXh4aWREcGVRaVhDUTAva0JpdHNSSnBXMTJTZ2lJZwo4
        STJBcWJkM0EzZTVwcUpKN2VGUzFLTUpza3dxQVBEMVhyK3dKejNucmpzCi0tLSBD
        dHFJZlZBcWhvSDloY0gyc1hBSE45aWpVK0hMaGZFK2VDWmdCTjRnTE1RCsl1KUla
        lcg+NUCIvhXXUWTmbkNxIg1KdqwT0zTynu7TV39l3KhBCn2ZAdmBnMICYigQ4cOZ
        jDwOwwTg7TSq0bY=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T01:43:52Z"
  mac: ENC[AES256_GCM,data:5iAlbmgBpNeG8Y/oj4u06JryE8wbFl7owJyKt6rlpkwGiS5Fzrde0lOn5cBJC75LfcpRQknLWaxl/Z8l0u07RADttsvki45V8Se/+35rTHu3djeMtojahI5/7wBwzwzFcK+QeXRQmfXQYYR2mNoe2QpkDVeXnTzjGOiUWWH3U6U=,iv:PEzzXzQhmBdAeIq0GPuhsCrgP+lpXCj+gIhuBRaQkaU=,tag:XoOKgqxorWHK3HAqByE6qQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
