apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deneb
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr-deneb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr-deneb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr-deneb
    spec:
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: deneb-config
        - name: deneb-medias
          persistentVolumeClaim:
            claimName: pvc-medias-deneb
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.16.2944-ls300
          envFrom:
            - configMapRef:
                name: deneb-config
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: deneb-medias
              mountPath: /synology
#          livenessProbe:
#            httpGet:
#              path: /ping
#              port: http
#            initialDelaySeconds: 5
#            failureThreshold: 3
#            periodSeconds: 90
#          startupProbe:
#            httpGet:
#              path: /ping
#              port: http
#            failureThreshold: 30
#            periodSeconds: 2
