resources:
  - ../common
  - ../../infra/common/csi-driver-nfs
  - actual
  - autoupdate-teable-figurines-currencies
  - etherpad
  - gitea
  - glance
  - gotosocial
  - immich
  - karakeep
  - opengist
  - outline
  - paperless
  - planka
  - publicfiles
  - qui
  - radicale
  - renovate
  - suwayomi
  - tasktrove
  - teable
  - vaultwarden
