---
- name: Create certs folder
  ansible.builtin.file:
    path: /etc/certificates
    state: directory
    owner: root
    group: root
    mode: u=rw,go=

- name: Generate certificates
  with_items: "{{ domains | dict2items }}"
  loop_control:
    loop_var: domain
  ansible.builtin.include_tasks: make_cert.yaml
