apiVersion: v1
kind: ConfigMap
metadata:
  name: gotosocial-config
data:
  GTS_HOST: fedi.prettysunflower.moe
  GTS_ACCOUNT_DOMAIN: prettysunflower.moe
  GTS_TRUSTED_PROXIES: "10.217.0.0/16"
  GTS_INSTANCE_LANGUAGES: en,fr
  GTS_ACCOUNTS_ALLOW_CUSTOM_CSS: "true"
  GTS_DB_TYPE: postgres
  GTS_OIDC_ENABLED: "true"
  GTS_OIDC_IDP_NAME: "ðŸŒ» Login"
  GTS_OIDC_ISSUER: "https://login.sunflower.lgbt"
  GTS_OIDC_CLIENT_ID: "d1e7c49a-b3a4-4dd4-a423-839e95981d05"
  GTS_INSTANCE_EXPOSE_CUSTOM_EMOJIS: "true"
  GTS_INSTANCE_EXPOSE_PUBLIC_TIMELINE: "true"
