resources:
  - ../common
  - ../../infra/common/csi-driver-nfs
  - anko
  - docker-registry
  - httpdebug
  - kakigoori
  - mazanoke
  - miniqr
  - ourfigurecollection
  - pocketid-remilia
  - pocketid-sunflower
  - prettysunflower-website
  - privatebin
  - uptime-kuma
  - vlmcsd
  - youtubethumbnails
