resources:
  - ../common
  - ../../infra/common/csi-driver-nfs
  - anko
  - docker-registry
  - httpdebug
  - kakigoori
  - mazanoke
  - masto-fe
  - backrest
  - enoko
  - miniqr
  - multi-scrobbler
  - ourfigurecollection
  - pocketid-remilia
  - pocketid-sunflower
  - prettysunflower-website
  - rallly
  - privatebin
  - uptime-kuma
  - vlmcsd
  - youtubethumbnails
