apiVersion: apps/v1
kind: Deployment
metadata:
  name: qui
  labels:
    app.kubernetes.io/name: qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qui
    spec:
      volumes:
        - name: qui-config
          persistentVolumeClaim:
            claimName: qui-pvc
      containers:
        - name: qui
          image: ghcr.io/autobrr/qui:v1.13.1
          envFrom:
            - configMapRef:
                name: qui-configmap
            - secretRef:
                name: qui-secrets
          ports:
            - containerPort: 7476
              name: http
          volumeMounts:
            - name: qui-config
              mountPath: "/config"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
