apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
data:
  PAPERLESS_REDIS: redis://127.0.0.1:6379
  PAPERLESS_DBHOST: 100.110.40.2
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://127.0.0.1:3000
  PAPERLESS_TIKA_ENDPOINT: http://127.0.0.1:9998
  PAPERLESS_URL: https://papers.prettysunflower.moe
  PAPERLESS_TIME_ZONE: America/Toronto
  PAPERLESS_OCR_LANGUAGE: eng+fra
  PAPERLESS_EMAIL_TASK_CRON: "* * * * *"
  PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
  PAPERLESS_DISABLE_REGULAR_LOGIN: "True"
  PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
  GRANIAN_PORT: "8000"
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
  PAPERLESS_CONSUMER_POLLING: "10"
