emails_mailboxes_passwords:
  me@prettysunflower.moe:
    password: ENC[AES256_GCM,data:cNicBM+lcdphvY8en9XFrA==,iv:IQVawAxXdsH8PwjDwdgjn3qb86f/T0DdMlaIpqXBw2U=,tag:p1kpa/dFAgv1lSfgPac9Qw==,type:str]
  remilia@ecdfeaa2.moe:
    password: ENC[AES256_GCM,data:t3d0Z+JQ5f+apo2l+9NUbw==,iv:1rAgT99XhVHhY1E7SDcQVq/UaQCy4wKJnQplcJPRFPA=,tag:rOpdbFoSWoel93UFSzZ69A==,type:str]
  pixiv@remydcf.dev:
    password: ENC[AES256_GCM,data:epDU9EpuO5L5KKi9fJq+gQ==,iv:U9J2QMPtHEdSlZY52EV3dZXS2GT3mWxaTGiI12zIxdA=,tag:/2znmFpCgKDx4CJ40Rq/AA==,type:str]
  umontreal@remilia.ch:
    password: ENC[AES256_GCM,data:dgFsXrdrtkLxxchBGnxxhw==,iv:WHlp6QjUBRkuBpi45jriA39+O0WQqKc+A2V6UEeVOrY=,tag:1Ffr0m0MbvzGhzzLN0df7Q==,type:str]
service_emails_passwords:
  vaultwarden:
    password: ENC[AES256_GCM,data:jEI3JxediRaXOuN1yAA=,iv:0++ssn3ipXClXgJF7sPUvpQ4vCpejUecPKYRu/lPAN0=,tag:6WbwymU4VN3KIPfL6sZ6gg==,type:str]
  booklore:
    password: ENC[AES256_GCM,data:bBBFKjzvODH7zx40a88=,iv:AkUPkXQChbKgjvvYTtHuDn2HsXVaWLM70gVvUxcgMRQ=,tag:v9Fb0u+nzRyhNsOrFE2dgA==,type:str]
lego_env_api:
  BUNNY_API_KEY: ENC[AES256_GCM,data:MXQeAlCgL/r5ugVPBXmYnMxLgLusuPAB1LGSgHt7QD8QCbWNK4i6Y0d7GjblmiBfQfjpI4ubNT1OpAAsDP3bQQcFwoGv0atB,iv:5H2f2n5JMxu/2nkCFg4VlRShSUfHrOLJ+YUdvvHrHNg=,tag:CMuVm/2bhKIiiNC4uDKJCw==,type:str]
  PORKBUN_API_KEY: ENC[AES256_GCM,data:kDWCvOYiN1fW15bvJ65iJ7iWaBJKN3BA4AzaQfPkLBWtHbs7MnnWl0SOk5+5E5RwUgBG86fkyE0EJ4a0wst2Nwjn3+E=,iv:EHlrVi0hMzto+Us+Qa5aDt74r6Ou2d+wpfD5ENzQ8II=,tag:qj3wmU6q61mZpNh+JLc78Q==,type:str]
  PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:PuNfASSV/Rqxbme4RDWYfNPHaf5q/gK4cNbf4lm1pfLF+J8mki67QSDKe7cCK3DV7IhyqxTN9jrCXJO3jvfs6jMWS6s=,iv:iwDeYW+mky24as8cSWuwxb/gKOpXh8rHt7o8J09zEOk=,tag:FnJnggw/gxxVhNTEtpgO/A==,type:str]
mysql_password: ENC[AES256_GCM,data:74rIFzqbvFEADzYrf3IQy2yH3XYG5ek02w==,iv:VfUkaJ19W1Hwtdjk4rVsmJ0IcIYnG2a4oeiiuKCeD/4=,tag:9ZO3inejWFU8y7HvFivRhQ==,type:str]
sops:
  age:
    - recipient: age1pq15jdu8xuhs350gqry8d0qc3q48y26jmdye55utf4dwrz0usxd7cje7v4sjm92k0spkw3kg2zxezvjr4vyk8dtsqn5trzmr5xzm02f20urxta9kgsa4zh7c7ttzrpssg86naua3dw8j9e479mspcugt89rq047hd4zks9m4kr86xqpttfvzmx3gmphsa3fg962ecm472w8kna2e2hcqf0267regfr9z55p932gnqshms732gj3mxec3399fuhzxkdtrwqf4dra8ngy9z79hh67rjguqfzkh63x2dszfsrrszr4cxm6w0qftequn5ts3nfryx3lyshr02rp8z9yms5qqurpvg8w003zj97aaxejde5ne795pmgy03sm57dgelqp9kd9svguvd7r2thmcpaqxk2x8mjmety4e85lpnt3fph0d8z0evzj49fg2mg4d2qmkam3e5y9jfzhnwt5z5t4g80dgqg2ua32rp63nfmpql58z03cykc6jnpcdt9mqr4n387ss0p9996m0efwxzv2hhvpdsehp90vl28s4udqkmxy0dy49tglyzntx4d9nwg3pkvyeh99zvha024pnqrcey7qt7x22l2nv04ynpnwx3jhnguu06jm60ffvackp0a5ashp4wtfkq949dlnga8vq2s5a2pcfqycrk3uz8n6r7gz283rv5xeacf4l03sepjhrg0wrgmf5m8r0cjzettmekuh820dj5un5x30q36hr35h6gy9y2g8sum36yflaj3g5jmqtah8y94427k2xkt204fd4ev2zqrv898rnrvquu5u0qgwfp6kl82yypt5pq5qey3ffq25sfyk4q0h2yluv3d0h9s0yxa74fp3gtcxc0yyqejtyz3vjz52hv6qmxw8sg6049s576wfqps6sueq90zngafk2tc7xwq8fffzcdw2yzsswg3w90zg5tyy37xt056xxmmzdcvqefqyxgzn05mdgnt3yhz6yqslq9q8lp3tuv29hjazvz0edudfvaccygx5xwejq84c8a39frd6r2th4wf05srxg9kgj3x5jjdgtrwsz0y5t653tmufnny5c4ghgdaq6s4qvuungax9z2m63h40srvv0qw6cq3vgkgruf0mrcaljk6gqaalvq2zn3fhy9gm404qsqy0w9vyaky9ggukvpjfscmujqatguhta5c80ye5634h2sukq7wwdv2kykpwc5je4lpvp6z7ss64xuhsl7vzz2d2z7aftd550j4p2k27pxepf8fj6xu4t0jgrqvluqd9ffkpttjgtr0mwynppwj757l4heyjr9exl35gj2x5y6pfk42qywpeuuvvsa93wad3j7rvej7qk9glqjt830r55l6cydc34pk9xpn9fk32kq5hzukrqz2zy9nfecf3swcqkuqf2lty5l2tpgxk45zudww9uht8numeeplde360mxv2qe35vkf6p86fw9wfkp7pw2gpeys3wmjzjw2vty8xjdjqpaaxmzm8zz42rvw2xkqyq4xvjyp3tpv5auq6hgltfp4alzexxtzdcdgsauk89dd0qypdk9jynfaeqcvxzukmz3rtxcm8652z2aaer6crzuh54e6mrx5632xl9vxtrhy6qz4ftqehx375gp4eh7s6gp6qm36kjef02alpzqgrn3mlxc2cj3r8hrga5r8uhsp8vzg3nkf5r8rm2dyk9vhdq3d889z4z9d4gj4myqmte0sp6k0e33ff9xq4y7g48p090ym9fjuralz09gru0lck2xe5x3avq2lt58pjadghjar3nt34klh0ds7lfuacqt44lrgpy2fcv9twslydqvvghycra0usmg9emytdhr5x2f86jqz0lrz38l4k9srfq385z7ewugskeffgkv5ysdzpz86yme6t4jk3fuarhqg6sarf7srp26wqzcwdmrtv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVxTUdNajNj
        SWVmQ1VPc0x4T1BmWEtBMDBrY0hkbyt5VkFWUkVNM1NMam11cUxXamlwN0tJSGEv
        THJvTkNHcE1zNTYrSzBGaURIQnZ3UDJSeXpSTGlxcklOaE1RRzRBUkVYNGJOVmpN
        cy94cng4dG9kTE1CL1FWVzdJT1NoSVZTb01Zc1lJSjNRelozVjM1YXR5WHZrOHpz
        bTY0SnAzcld2YVVTTk44bFdLdU1LZ3c4a29BWFRRL0g3QzA1dDd1emJOKzZiMy9t
        amRrUlRtZEc5aTl4RkRXRDlyMlZNNWppa3prS2licXlSVnBtcnZXN01sbmM2RGw4
        RVZaVEFQWDZKbFJCcDJmVWlNRXVtVlp6NE05YXRXV0d4TXZPWmM4REd3WGQyMmlW
        bVYyVWJqSStBZEJxYkZQSWYyVkJLRjJYd05sYnRXUVhuakpTZ1paeU5zSXhJc090
        Tk92MmtmbUphb3hCdTE4RVRwVTVKVXh6UlNoRG9OS05CZWxGYTVrMVpFSnJGa3hh
        NHVXN0lLalJvRUQ0cnh6eThaOVhjTit2VkkzL1BFamU3TkJBaGpHRzh5VjE2RVNo
        TVZjbnVjZ0JvMkQzZm1CMUhOeWRPQlVsZzNlUjBwU3dTUE5BSjNMS3RHNnZ2aFRJ
        YS9xcCs1NFRYTmsycGYrc0xPUEFkY0xWRTVZenFCZjlhMCtzQUgrZlhnODJMSkRF
        aDNUSTl4Vit5alhDZHpMRkFwNW9BNmgyOGVtdk9JaFpLUXB1NlYwRjlmWGpDbTVq
        Z2h2d0J1V2o3cUNUMHlBMURiQ1JFQ3BMbENtVWMwdXZualVJaVhXMEx4dy9KcTE2
        b3Y2cUtjTEw4cDVLSDBySkhTNTRBUTBwdUJvTnJ1c042MmxJVjV6NGxGLzdtdGYv
        NlkxS1BTaTkyMFRYQXBFZnhYNnhOS09tV096OUJBSW1tYlJwR0gwMVYvV1gxUHoz
        Z3UvOWVnTTN3ZXY2QUdZVzI4SWhBTkNVendjazF4WlQvdXI3QWI2QkRSQUhFay9S
        WCtNUCtJRmVFWHFoNWlYejhrdzBMc1Y1SGF0NllHd1pmV3ZFOVREeWt2RDZzUjls
        TFF3MENHbGVlVVc5L0I5dy9Xa1FxZUFFS1NCUzVVc3p2a1U1V1h0UzFHeFVSSUhs
        QXN4VTJmbjFFaS9sdUdPam5BUm9lbE5Ub1lUcGwrZFZWZmFBWk5hSFp1MWVXTTh1
        L1hidlBMZG5YTGwzTzZxQnFJeGtHT0s1YkQ1d1ZQd3ZnOXRoZUJxZE10eUMvQllN
        NEtpQkhRUFRXM2l4V0c2amdKL3FBaUp4aDB6YjRSYVpUV043dWowaEZxRyt4RWFj
        Y2VGNlZsWU1DWWk2a1BFRTBOa0t2OVNNUzBVV2xBRDhCZytXcXd0eXhtRnBCbjRE
        N0xBOGhRN253WHhiRlNaVXpFWXBCUGNBUHp4YVVueXNlU2hpaDZwSmd6bGFwQzV0
        YkJRSkdjVi9FTEJnSzgzRjVvdy9DZ1Q5WDg4c1NYRG0vR2VDREwxelFwNWpXb3or
        QmJ2RFFOVXE2U3MvbnlLdFgyRWtTbjU5RUorbHFrTGJ4WU92bmVaN2FLYitseWVT
        Z0lndTRFbjNOUkNBY01NN3U2SUp3bmR6SXpnQ01tOGFkUXhjYU1WV1NiR25pVTlW
        Rm5WUXVrZDZ0bTJXaEJRdjdEQ1FXa0FhMmJqbUpSeVE4a0VkbEZ0OWdzOWd6akhV
        cWU1dlNJYkpSREZPRXFlMHJ6NklmdmQ0b25PcUozdGo0YzFTYjVNK1NCdmFDcm16
        K1pSWEQvZjVVaFAyQmtYNmlCd1lWdzZlcUdmaUtTVHRYQndDaXZNSzJRWDlwVVk0
        RG44V3dmcVV6OTRORGFLQnVrM0dkMTFKNit1ZGd5VWF3N3ByV25SRmE4RHhPclh4
        cFp4UkJvVnJCekx1OHFiMHQwQnlERjlNY0hERWhHUFZoWjk0ZlYrbDErNE1PUQp2
        aFVNNDVORklEZ09ucCs5WTRHSEJ4eW1wSHhFci9KL0w5WENrbzRDcE00Ci0tLSBi
        S09HdnVPN001LzF1SlhUVEVYV2ZEWEd0U1paL084dnRrY2Z6WnRuVnpNChzlvRP5
        c5XqhUo+3vFd2z0ZU2xOr5ciLcm64GpcqThqiq5JHIKpMHg8jCRwPboUNehBGEOx
        KXMbpkQ6xHyt/40=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T03:49:07Z"
  mac: ENC[AES256_GCM,data:sY8pjmq5ooBmoxe8xnD5yIJT8cemWQP8w5A5ee94vClj5ifwTcqdaVBnrjOS66+udk33kcr6s8r2ZeBxl11efBLSJSn4qx15oFctZI/lKbY7u4cVddFBpgVbjygTnuQmEGTmIyrqV1rNKsblz8zXw0eW/wiJyJhBkIEnhpXleEM=,iv:FwEvac68qqaHI3vHph44t0zL9CIIzYoIQ2gJAAu2xYY=,tag:CkFlhq2BzSzT7Sfo2j7rng==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
