---
# - name: Install packages
#   ansible.builtin.import_tasks: install_packages.yaml

- name: Setup database
  ansible.builtin.import_tasks: database.yaml

- name: Setup OpenDKIM
  with_items: "{{ domains | dict2items }}"
  loop_control:
    loop_var: domain
  ansible.builtin.include_tasks: opendkim.yaml

- name: Setup Postfix
  ansible.builtin.import_tasks: postfix.yaml

- name: Setup SpamAssassin
  ansible.builtin.import_tasks: spamassassin.yaml
